
# Dependencies
FROM node:22-alpine as deps

WORKDIR /usr/src/app

COPY package-lock.json ./
COPY package.json ./

RUN npm install

# Builder
FROM node:22-alpine as builder

WORKDIR /usr/src/app

COPY --from=deps /usr/src/app/node_modules ./node_modules

COPY . .

RUN npm run build

RUN npm prune --omit=dev && npm cache clean --force

# There could be an additional step to run tests


# Production image build 

FROM node:22-alpine as prod

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist

ENV NODE_ENV=production

USER node

CMD ["node", "dist/main.js"]







